### PR TITLE
Replace broken hash table with mostly-STL functions.

### LINKED ISSUE #1: Implement non-limited hashmaps in SPASM (hash.cpp)
Current hashmaps have a pre-defined constant size limit. This could cause problems in the future with larger assembly programs. Could this be fixed?

### PR DESCRIPTION
**Pull request by tari**
Fixes #1, with concepts that were kind of abortively present in the code already.

Potential issues I see:
 * Use of `std::unordered_map` requires C++11
 * Removes the packaged GMP header

The included gmp.h seems to not compile correctly in C++11 mode, but I think it's more correct to remove it anyway since it's a set of declarations that are not at all guaranteed to match the version of `libgmp` we link against. This is mostly a concern for Windows where it'll require a bit more system-specific setup I think.

Tested by compiling a small program under Valgrind and everything appeared to work correctly.

### CODE REVIEW

**Comment by alberthdev** [comment]
Wow... you are crazy fast with this stuff!

Indeed, BuckeyeDude did attempt to re-implement the hashmap with `std::unordered_map`, but it was a very broken implementation that I ended up tearing out. This seems to be a proper implementation!

With regards to compatibility, it's definitely a mixed bag. I'm not sure when GCC moved from `std::tr1::unordered_map`, but they seem to have support for quite a while. However, GCC had some performance regressions recently, referencing [this](http://stackoverflow.com/a/11634689/1094484) and [this](http://www.mail-archive.com/gcc-bugs@gcc.gnu.org/msg368041.html). I didn't get a chance to test, but presumably the later versions fix this issue. 

With MSVC++, it's also kinda interesting. It looks like they support the draft of the spec since VS2008 (`std::tr1::unordered_map`), but didn't fully integrate it until VS2012 (`std::unordered_map`). On VS2010, there seems to be [some issues](http://stackoverflow.com/questions/6859915/mysterious-behavior-of-unordered-map-in-visual-studio) with the implementation. Other than that, nothing too big.

I guess the main issue would be detecting the compiler support. For GCC, if people are using a "stable" distribution (e.g. RHEL/CentOS/Debian), detection is going to be necessary. For more bleeding edge distros (e.g. Ubuntu, Mint, Arch), this won't be too much of an issue.

For MSVC++, it might not be too bad, since we can just say that VS2012 or newer is required. Of course, the question would be whether using `std::unordered_map` is worth axing support for VS2008 - VS2010. (I haven't tested VS2008, but VS2010 does compile SPASM-ng just fine.)

As for `gmp.h`, removing this header would pose issues on Windows, since MSVC is expected to use said gmp.h (and the GMP/MPIR pre-built libraries in `lib/`). It's possible that we could upgrade GMP/MPIR - both the compiled libraries and the header - and perhaps potentially mitigate this issue.

It's interesting that you had that issue, though... I would assume that this is an issue on Windows, since Linux/Mac isn't set up to use the local gmp.h. Just for fun, on Linux, I changed the header to the local one, and made sure that the system one wasn't getting read. I added `-std=c++11`, and then recompiled from scratch... no errors! What system/environment did you compile on to trigger this issue?

At the moment, I'm not so sure whether we want to go with this or not. When I was working sometime before on this issue, I was also looking into alternative hashmap implementations written in C/C++. Just to explore, maybe we should take a look at those alternatives and see if they work? (Supposedly, `std::unordered_map` should be seriously fast, so it might be tricky to find something close! But then again... we're not hashing millions of entries, maybe <100k at most, so speed differences can be negligible. [This](http://incise.org/hash-table-benchmarks.html) is an interesting benchmark of a few options out there.)

What are your thoughts?

**Comment by tari** [comment]
> As for gmp.h, removing this header would pose issues on Windows, since MSVC is expected to use said gmp.h (and the GMP/MPIR pre-built libraries in lib/).

Ah, I missed that those are in there. Might be nicer to move gmp.h into the `lib` directory as well to avoid further confusion.

>  I added -std=c++11, and then recompiled from scratch... no errors! What system/environment did you compile on to trigger this issue?

It may have been a transient error flushed out by some bug as I was developing, who knows. I'm on GCC 4.9.2. I'll put that header back in and see how it goes.

> I was also looking into alternative hashmap implementations written in C/C++. Just to explore, maybe we should take a look at those alternatives and see if they work?

I'd rather not pull in any more external dependencies than are really necessary (even if they can be embedded in our source tree). Even if some common implementations are slow, I rather doubt they're so slow as to be a real issue on our workloads; it's not like we're trying to serve 10k network clients at once.

Compatibility-wise, using `std::map` instead drops the required library compatibility down to C++98, which should be supported by any sensible compiler in use today. The downside there is we take a performance hit since the ordered map is usually implemented with an RB-tree and so has lg(n) lookup and insertion complexity. Given the largest programs people work with today have around 8000 labels, a ~15x slowdown might be plenty acceptable.

**Comment by tari** [comment]
With my gmp.h changes reverted:
```
$ make
g++ -std=c++11 -I.  -DUSE_REUSABLES -DUNIXVER -DUSE_BUILTIN_FCREATE -c main.cpp
In file included from ./gmp.h:52:0,
                 from stdafx.h:81,
                 from main.cpp:1:
/usr/include/c++/4.9.2/cstddef:51:11: error: ‘::max_align_t’ has not been declared
   using ::max_align_t;
           ^
```
The problem is that it adds the working directory to system include path so `#include <gmp.h>` pulls in the one in our source tree rather than the system one.

**Comment by alberthdev** [comment]
Oh... didn't realize that you removed `gmp.h` *completely* from the source (including the `#include <gmp.h>` for Linux). Yikes! That would have really broken support for app signing...

It's interesting that your compiler opts to take the header file in the current folder rather than the header file in the system... I'm not totally sure what's the "correct" behavior, but I'd assume that using `<something.h>` would use the system version, not the local version!

I think there's a simple solution for this little `gmp.h` - just rename it to `gmp-windows.h`, and then change `#include "gmp.h"` to `#include "gmp-windows.h"` under the `#ifdef` for Windows. That should fix the header conflict. Of course, this means that `SPASM.vcxproj*` will need to be updated as well.

As for the hash table, maybe I should've clarified - I was looking for small hash table replacements, not a full blown enterprise hash table library! Indeed, linking those benchmarks was a bit silly of me, since they are mainly testing those kind of libraries. Those kind of libraries would bring too much overhead.

The libraries I'm interested in are TommyDS (hashlin/hashdyn) and KHash. Both are pretty darn fast, relatively small, and seem to be faster than `std::unordered_map`, at least according to TommyDS's [benchmarks](http://tommyds.sourceforge.net/doc/benchmark.html).

As for size concerns, I stripped out any code that wasn't necessary for the hash table implementation, and then compiled it to see how big the implementation might be. Not exactly the most scientific, but here you go:

```
Original hash.cpp
===================
(after tearing out some includes and making it "independent" from SPASM-ng)

No optimization
-rw-r--r-- 1 albert albert 4368 Mar 30 20:14 hash.o

-O3
-rw-r--r-- 1 albert albert 4720 Mar 30 20:14 hash.o

TommyHash Dynamic
===================
No optimization
-rw-r--r-- 1 albert albert 5120 Mar 30 20:16 tommyhashdyn.o
-rw-r--r-- 1 albert albert 3960 Mar 30 20:16 tommyhash.o
-rw-r--r-- 1 albert albert 3912 Mar 30 20:16 tommylist.o
Total: 12992 bytes

-O3
-rw-r--r-- 1 albert albert 3600 Mar 30 20:16 tommyhashdyn.o
-rw-r--r-- 1 albert albert 3072 Mar 30 20:16 tommyhash.o
-rw-r--r-- 1 albert albert 2440 Mar 30 20:16 tommylist.o
Total: 9112 bytes

TommyHash Linear
===================
No optimization
-rw-r--r-- 1 albert albert 6216 Mar 30 20:17 tommyhashlin.o
-rw-r--r-- 1 albert albert 3960 Mar 30 20:17 tommyhash.o
-rw-r--r-- 1 albert albert 3912 Mar 30 20:17 tommylist.o
Total: 14088 bytes

-O3
-rw-r--r-- 1 albert albert 4752 Mar 30 20:17 tommyhashlin.o
-rw-r--r-- 1 albert albert 3072 Mar 30 20:17 tommyhash.o
-rw-r--r-- 1 albert albert 2440 Mar 30 20:17 tommylist.o
Total: 10264 bytes

KHash
===================
NOTE: KHash is very C-macro-y

No optimization
-rw-r--r-- 1 albert albert 1073 Mar 30 20:18 khash.o

-O3
-rw-r--r-- 1 albert albert 929 Mar 30 20:18 khash.o
```

Interestingly, KHash beats the original `hash.cpp` significantly, only adding around ~1k (versus ~4-5k). TommyHash adds about 6-8k, staying somewhat close to the original implementation.

Either way, we can still go with `std::map`, since the speed is really not a big issue. As mentioned before, developers are barely hitting 10k labels, and the performance difference is negligible at best.

**Comment by tari** [comment]
>  (including the #include <gmp.h> for Linux)

I reordered things a bit- it was still in there, just every platform was using `<gmp.h>` to search the system include path.

> I'm not totally sure what's the "correct" behavior, but I'd assume that using <something.h> would use the system version, not the local version!

It searches the include path, which explicitly has the CWD prepended to it with `-I.`.

> I think there's a simple solution for this little gmp.h - just rename it to gmp-windows.h, and then change #include "gmp.h" to #include "gmp-windows.h" under the #ifdef for Windows. That should fix the header conflict. Of course, this means that SPASM.vcxproj* will need to be updated as well.

[fd7f41b2](https://github.com/tari/spasm-ng/commit/7df41b232f6df64393dc412d6075fd1be74c62af) fixes the issue just by removing the -I option from CXXFLAGS. Windows build should work as normal and nothing else needs to be touched (the rest of the commit is just reverting stdafx.h and gmp.h).

---

I'm not so concerned about binary size, more maintainability. The more code we have in-tree, the more unwieldy it gets to mess with. I'm working on a quick patch to use `std::map` instead of `std::unordered_map` and I'll benchmark it to see if there's a major noticeable performance loss. If no, I'd say that's the way to go.

**Comment by tari** [comment]
In a not-very-scientific test, assembling [Phoenix](http://www.ticalc.org/archives/files/fileinfo/148/14876.html) with a `std::unordered_map` saves ~5 milliseconds over `std::map`, where the `std::map` implementation runs in about 70 milliseconds.

Seems to me like that's the way to go, given there's basically no difference in time (5ms is essentially noise, but it does seem measurably slower) and low complexity in using it, plus the trivial compatibility.

**Comment by alberthdev** [comment]
> I reordered things a bit- it was still in there, just every platform was using `<gmp.h>` to search the system include path.

Oops - didn't read that commit diff carefully. I stand corrected!

> fd7f41b2 fixes the issue just by removing the -I option from CXXFLAGS. Windows build should work as normal and nothing else needs to be touched (the rest of the commit is just reverting stdafx.h and gmp.h).

Oh, didn't think of that. Yeah, that should work since the other include files are generally included locally, so the `-I.` isn't needed.

> I'm not so concerned about binary size, more maintainability. The more code we have in-tree, the more unwieldy it gets to mess with.

Fair enough. You do bring up a good point - if there's a bug in the other implementation, we're pretty much stuck until they fix it. Might as well stick to either our code then (or, as you mentioned, compiler standard `std::map`).

> In a not-very-scientific test, assembling Phoenix with a `std::unordered_map` saves ~5 milliseconds over `std::map`, where the `std::map` implementation runs in about 70 milliseconds.
>
>Seems to me like that's the way to go, given there's basically no difference in time (5ms is essentially noise, but it does seem measurably slower) and low complexity in using it, plus the trivial compatibility.

Good choice of test (plenty of labels to play with)! And indeed, as I suspected, it's *very* negligible. (And I don't think the average user can feel the 70ms difference...) I guess the only interesting thing would be to see how the original `hash.cpp` compares performance-wise with `std::map`. Could you test that, out of curiosity?

One last thing - since we're not using `std::unordered_map` anymore, make sure to remove `-std=c++11` from the Makefile!

Otherwise, I agree on all counts - go ahead and submit that patch, and I'll happily accept everything in!

**Comment by tari** [comment]
> And indeed, as I suspected, it's very negligible. (And I don't think the average user can feel the 70ms difference...)

Just a 5ms difference; the total time to assemble as reported by the program is 70ms. I didn't bother benchmarking against the old hash table, but its collision behaviour is atrocious so I wouldn't be surprised if the new tree is faster than the old hash table in many workloads.

**Comment by alberthdev** [comment]
> Just a 5ms difference; the total time to assemble as reported by the program is 70ms.

Oh... again, I misread - sorry! That would be 65ms vs 70ms (`std::unordered_map` being the fastest).

Merged - thanks again for your help!

**Pull request merged**
