### PR TITLE
TI 83 Support

### PR DESCRIPTION
**Pull request by jamrootz**
I made some changes to add support for the _original_ TI 83 (Yes, I still have one of those :) )
- Added the standard include files (tokens and ti83asm)
- Added a _make83_ routine to properly format assembled code for TI-83

The previous version of **export.cpp** grouped the 83P in with other early calculators which all used the _makeprgm_ routine designed for 86S.  The resulting 83P file was the wrong format for the 83.  This modification produces working 83P binaries.

### CODE REVIEW

**Comment by alberthdev** [comment]
Thanks for the PR! One little nitpick - could you clean up some of the indents/comments in your PR? Once that's done... the only thing that I would suggest is to *potentially* merge your function into `makeprgm()`, just so that all of the logic is handled there.

Looking at `makeprgm()`, it's definitely pretty messy... it's not particularly obvious what is happening behind the scenes. I think we should try to merge the logic if possible... but if it gets to be too much, no worries about merging it.

I think that beyond this PR, it might be a good idea to try and rewrite some of the stuff in export.cpp to be clearer (and potentially more bugfree). One potential idea might be to use @adriweb's [tivars_lib_cpp](https://github.com/adriweb/tivars_lib_cpp), which seems to cover many of our cases so far, and seems to be pretty reliable given that it's in use in production in a few projects.

What do you think?

**Comment by jamrootz** [comment]
Hi,

I'm really sorry about the delay!  I didn't realize you had responded for a while.
I have no problem with some nitpicking, I would love to clean up the code a bit, but could you be more specific about what you mean?  To me the indenting looks reasonable and most of the comments were copied from your original function, I just added a few with my changes for clarity.
Again, I'm happy to comply with your style preferences if you let me know what they are :)

As for `makeprgm()`, I agree it's getting a bit bloated and confusing. That's why I moved the 83 code to a separate function.  A rewrite down the road is probably a smart choice, especially if you intend to cover other calculator-specific cases.

**Comment by jw0k** [comment]
@jamrootz Are you planning to merge it? I have a TI-83 too and I wrote a python script to convert incorrect output from SPASM to the correct 83p format. However it would be nice to have it fixed in SPASM

**Comment by alberthdev** [comment]
@jw0k Thanks for the reminder!
@jamrootz I should extend the apology likewise - when you responded, I did see it... but that was around a time when I was really busy, and I didn't get a chance to respond until now!

Regarding indentation, just match it up with the rest of the file. Make sure your editor is showing the whitespace so that you can easily spot any issues (Notepad++/Geany has such an option, and likely other editors as well).

In particular, some lines use the Pythonic 4 spaces, and most of the code here uses tabs - make sure to stick to tabs!

Finally, regarding `makeprgm()`, on second thought I think it would be useful to merge the code back into that function. As nasty as it is, I think having them in one place will save time later if we do end up rewriting this. If at all possible, could you please merge those two functions together for the PR?

Once that's all said and done, I'll take one last look at the PR and hopefully it should be good for merging in!

**Comment by jamrootz** [comment]
No apologies needed!
I definitely sympathize with time constraints, I am in a similar situation now :-/
If I get a chance, I will look back through the code and try to clean up the style.  I'm super primitive and use vim only, so I did not notice the inconsistent indentation. 
I'll also take a look at the makeprgm() function, but I can't promise that will be soon. 

Cheers!

**Comment by tari** [comment]
> I'm super primitive and use vim only, so I did not notice the inconsistent indentation.

Just to chime in with a suggestion, `:set list listchars=tab:>-` will make hard tabs show up as '>' followed by enough '-' to reach the next tabstop which makes it easy to tell what's spaced and what's tabbed.

**Comment by jamrootz** [comment]
Wow, that's a great tip!
Lesson learned, I shouldn't have been so quick to throw vim under the bus. I really just didn't think to look for this.  I have fixed the spacing on line 697, and I'll submit a new PR when I rewrite the makeprgm() routine. 

Cheers!

**Comment by jw0k** [comment]
In case someone needs the TI-83 support right now - I've published the script that fixes incorrect 83p files here: https://github.com/jw0k/ti83-tools (fix83p.py)

**Comment by jamrootz** [comment]
@alberthdev I finally got some time today, so I merged my TI-83 changes into the `makeprgm` function.
I think we should be good to go!

**Comment by alberthdev** [comment]
Sorry for the extensive delay - it looks good to me, merging. Thanks for the fix!

**Pull request merged**
